### ISSUE TITLE
Support for vector search

### ISSUE THREAD

**Issue by nitinsurya** [sanders41/meilisearch-python-sdk#826]
Official meilisearch-python currently doesn't support `vector_search`. https://github.com/meilisearch/meilisearch-python/issues/901

Could this feature be provided here?

**Comment by sanders41** [comment]
It is already available here. Did you try and have issues?

**Comment by sanders41** [comment]
@nitinsurya to use this feature make sure to first enable the experimental feature in Meilisearch with:

```sh
curl \
  -X PATCH 'http://localhost:7700/experimental-features/' \
  -H 'Content-Type: application/json'  \
  --data-binary '{
    "vectorStore": true
  }'
```

Then you can add embedders either with `update_settings` or `update_embedders` which are available on both `AsyncIndex` and `Index`. 

I'm going to go ahead and close this, but if you have tried this and are having issues feel free to reopen.
