### ISSUE TITLE
TypeError: no default __reduce__ due to non-trivial __cinit__

### ISSUE THREAD

**Issue by Jakal02** [sanders41/meilisearch-python-sdk#848]
When creating a simple FastAPI application, and linking it up to Meilisearch using the async sdk, any response that includes a reference to an async meilisearch object throws the error described in the title. It seems that there is no __reduce__ method for the AsyncIndex object. See the first comment on [this StackOverflow](https://stackoverflow.com/questions/69032946/python-process-typeerror-no-default-reduce-due-to-non-trivial-cinit) post for more clarity.

## Steps to reproduce issue and desired behavior
I am working in python 3.10

### 1. set up python project and paste this code into `main.py`
```{python}
import os
from fastapi import FastAPI
from meilisearch_python_sdk import AsyncClient

client = AsyncClient(
        url=os.environ.get("SEARCH_INDEX_URL"),
        api_key=os.environ.get("SEARCH_INDEX_KEY"),
    )

app = FastAPI()

@app.get("/health/")
async def get_health():
    return await client.health()

@app.get("/create_index/")
async def make_index():
    return await client.create_index(uid="cool_index")

@app.get("/get_index/")
async def get_index():
    temp = await client.get_index(uid="cool_index")
    print(temp.__dict__)
    return_dict = temp.__dict__
    return_dict.pop("http_client")
    return_dict.pop("_http_requests")
    return temp.__dict__

# just so you can easily delete the index
@app.get("/delete_index/")
async def delete_index():
    return await client.delete_index_if_exists(uid="cool_index")

```
### 3. Navigate to `localhost:8000/health/`
The response should be {'status': 'available'}
### 4. Navigate to `localhost:8000/create_index/`
This will give a 500 internal error, even though the response went through. **This is the error**
### 5. Navigate to `localhost:8000/get_index/`
This will give a 200 OK response. **This is the expected behavior**. The response will look something like the below screenshot:
![image](https://github.com/sanders41/meilisearch-python-sdk/assets/37743499/c030f055-c433-4227-8c96-a54d06b644f4)

### 6. (optional) Navigate to `localhost:8000/delete_index/`
This will give a 200 OK response and delete the index.

The `http_client` and `_http_requests` keys have values like the following when printed:
```
{ 'http_client': <httpx.AsyncClient object at 0x7f06dc911750>, '_http_requests': <meilisearch_python_sdk._http_requests.AsyncHttpRequests object at 0x7f06d9187790>}
```

**Comment by sanders41** [comment]
I think the error comes from returning an `AsyncIndex` from `make_index`. Do you still get an error if you change `make_index` to:

```py
@app.get("/create_index", status_code=HTTP_201_CREATED)
async def make_index():
    await client.create_index(uid="cool_index")
```

**Comment by Jakal02** [comment]
You're right, I don't get an error! But, I have a question: what is best practice for returning information to the caller of my API endpoint like I do for `/get_index/` accessing the dictionary and popping keys? Working with the official Meilisearch python SDK, calling [get_index()](https://python-sdk.meilisearch.com/meilisearch.html#meilisearch.client.Client.get_index) returns type Index and that serializes to something without error as desired (maybe it cleans up other fields I don't see, I don't know).

## See serialized Index with official SDK
Change the relevant lines of code from the original Issue post and make everything synchronous. Below is the function of interest.
(switch AsyncClient for Client where it is defined). 
```
from meilisearch import Client
...
@app.get("/get_index/")
async def get_index():
    temp = client.get_index(uid="cool_index")
    return temp
...
```
And the output is:
![api_screenshot](https://github.com/sanders41/meilisearch-python-sdk/assets/37743499/68b8e328-2d15-4501-bc72-94fe8b078d97)


Also, I notice that other API's from the Official Meilisearch Python SDK return type TaskInfo so that consumers can get relevant information when the task completes (Create Index for example). These serialize too, returning the taskID among other things. Is it best practice to hand back that information directly to the client, or return something else to the client after hitting your endpoint which calls meilisearch?

**Comment by sanders41** [comment]
Best practice in FastAPI is to return a pedantic model. You can return a dictionary, which is why the official package works, but this wouldn't be the recommended way. TaskInfo is a pedantic model so it will return fine, but will most likely be unuseful in a FastAPI context. One difference in the official package and this package is `create_index` returns the index here so you don't need the task info. 

If you want some examples check out https://github.com/sanders41/meilisearch-fastapi. I haven't done much to maintain this lately but it will be good for examples.

**Comment by Jakal02** [comment]
This was very helpful. Thank you. I'll close this issue because I've learned that this "bug" is only brought to bear through user error.
