### ISSUE TITLE
`task_uid` absent in Meilisearch response

### ISSUE THREAD

**Issue by bbeattie-phxlabs** [sanders41/meilisearch-python-sdk#991]
Following the example set forth in

```python
from meilisearch_python_sdk import AsyncClient

async with AsyncClient('http://127.0.0.1:7700', 'masterKey') as client:
    index = client.index("books")

    documents = [
        {"id": 1, "title": "Ready Player One"},
        {"id": 42, "title": "The Hitchhiker's Guide to the Galaxy"},
    ]

    await index.add_documents(documents)
```

I've tried using this against a new instance of Meilisearch as per https://github.com/ezpaarse-project/meilisearch/blob/master/docker-compose.yml.

I get the following exception:

```
  File ".../lib/python3.12/site-packages/meilisearch_python_sdk/index.py", line 1530, in add_documents
    result = TaskInfo(**response.json())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../vox/lib/python3.12/site-packages/pydantic/main.py", line 176, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for TaskInfo
taskUid
  Field required [type=missing, input_value={'uid': 6, 'indexUid': 'b...14T00:41:25.158480803Z'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
```

Indeed, the content of the response from the Meilisearch instance I'm running is `{'uid': 6, 'indexUid': 'books', 'status': 'enqueued', 'type': 'documentAddition', 'enqueuedAt': '2024-07-14T00:41:25.158480803Z'}`, which understandably doesn't match the TaskInfo Pydantic model you've defined.

A discrepancy of expected response format perhaps?

Worth noting the records _do_ end up in the index.

**Comment by sanders41** [comment]
v0.25.2 is a very old version of Meilisearch and there have been a lot of breaking changes since then. The current Meilisearch version is 1.9, but anything >= 1.0 should work without issue. 

Alternately you could look through the releases and find the last supported a Meilisearch version that old.

**Comment by bbeattie-phxlabs** [comment]
Good catch. Image updated, fix confirmed.
